### ISSUE TITLE
Problem in Laravel 5.2

### ISSUE THREAD

**Issue by mgolshan** [srmklive/flash-notifications#2]
Hi,
It seems it doesn't support laravel 5.2

> FatalErrorException in FlashAlertServiceProvider.php line 61:
> Call to undefined method Illuminate\Foundation\Application::bindShared()

Is there any way to fix the problem?

**Comment by srmklive** [comment]
HI,

I have corrected the issue and tagged it in another release. Kindly **composer update** to update the package to the latest version.

**Comment by mgolshan** [comment]
Hi,

Thank you.
It's great.

I think it's better to mention in your readme file that we have to add @yeild('styles') and @yeild('scripts') in our main view file.

regards
